const mdLinks = require('../');


describe('mdLinks', () => {
//**DETECTA SI ES UN DIRECTORIO VALIDO
//CONVIERTE A RUTA ABSOLUTA
//DIFERENCIA ENTRE RUTA DE ARCHIVO Y DIRECTORIO
//ENCUENTRA LOS DIRECTORIOS DENTRO DE LOS DIRECTORIOS
//DETECTA CUANDO ES UN ARCHIVO MD
//ENCUENTRA LOS LINKS
  it('should...', () => {
    console.log('FIX ME!');
  });

});
